spring:
  profiles:
    active:
      - production
  datasource:
    url: jdbc:postgresql://db.icivegiybcedgshmfznr.supabase.co:5432/postgres?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 6462@Saha--
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 80MB

jwt:
  header: Authorization
  secret: "3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeThV"
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

server:
  port: 6200